version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: l2test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    container_name: backend_container
    restart: always
    depends_on:
      - database
    environment:
      SPRING_DOC_API_DOCS_PATH: /api-docs
      SPRING_DOC_SWAGGER_UI_PATH: /swagger-ui.html
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/l2test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8080:8080"

volumes:
  postgres_data: